### ISSUE TITLE
Prometheus Storage Path

### ISSUE THREAD

**Issue by gucarreira** [badtuxx/giropops-monitoring#5]
No dockerfile do prometheus o storage aponta para: _--storage.tsdb.path **/var/lib/prometheus/**_.

Olhando no _docker-compose.yml_ o volume está apontado para **/prometheus**
```ymal
prometheus:
    image: linuxtips/prometheus_alpine
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
```

Com isso sempre que se atualiza o _conf/prometheus/prometheus.yml_ o swarm cria um novo conrtainer e perde os dados.

Acredito que o mais simples é alterar o docker-compose.yml para atualizar o volume.

```ymal
prometheus:
    image: linuxtips/prometheus_alpine
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
```

Gustavo

**Comment by mayconfsbrito** [comment]
Realmente, está acontecendo isso comigo também.

**Comment by gucarreira** [comment]
Troca no docker-compose.yml a linha
```yaml
- prometheus_data:/prometheus
#por este
- prometheus_data:/var/lib/prometheus
```

Comigo funcionou

**Comment by badtuxx** [comment]
Done! :D
