### ISSUE TITLE
Can we integrate backbox_exporter to monitoring websites and http services?

### ISSUE THREAD

**Issue by mayconfsbrito** [badtuxx/giropops-monitoring#7]
Hi!

The currrent stack are enough to monitoring http services, APIs and websites or can we integrate the another service like blackbox_exporter?

**Comment by rocavalcante** [comment]
Hi @mayconfsbrito !
Yes! it is possible to integrate with blackbox, I made a project fork and inserted the blackbox.

https://github.com/rocavalcante/giropops-monitoring
